language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - chmod +x gradlew
  - sudo apt-get update -qq
  - sudo apt-get install -y firefox
script: - ./gradlew proguardCheck